### ISSUE TITLE
Reverse for 'process_payment' not found. 'process_payment' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by AhmedSalam22** [jazzband/django-payments#396]
![image](https://github.com/jazzband/django-payments/assets/35177448/d2252491-1ff4-4e5b-8aa6-64a2429c6e9d)
`
Traceback (most recent call last):
  File "C:\Users\admin\wwork\env\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\admin\wwork\env\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\admin\wwork\ok-api\openbook_payments\views.py", line 21, in payment_details
    form = payment.get_form(data=request.POST or None)
  File "C:\Users\admin\wwork\env\lib\site-packages\payments\models.py", line 143, in get_form
    return provider.get_form(self, data=data)
  File "C:\Users\admin\wwork\env\lib\site-packages\payments\paypal\__init__.py", line 228, in get_form
    payment_data = self.create_payment(payment)
  File "C:\Users\admin\wwork\env\lib\site-packages\payments\paypal\__init__.py", line 261, in create_payment
    product_data = self.get_product_data(payment, extra_data)
  File "C:\Users\admin\wwork\env\lib\site-packages\payments\paypal\__init__.py", line 216, in get_product_data
    return_url = self.get_return_url(payment)
  File "C:\Users\admin\wwork\env\lib\site-packages\payments\core.py", line 127, in get_return_url
    payment_link = payment.get_process_url()
  File "C:\Users\admin\wwork\env\lib\site-packages\payments\models.py", line 185, in get_process_url
    return reverse("process_payment", kwargs={"token": self.token})
  File "C:\Users\admin\wwork\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\admin\wwork\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /payment/6
Exception Value: Reverse for 'process_payment' not found. 'process_payment' is not a valid view function or pattern name.`

**Comment by WhyNotHugo** [comment]
Can you share you `urls.py`? 

Did you add the URLs mentioned in the documentation? https://django-payments.readthedocs.io/en/latest/install.html#configure-django

**Comment by vhsantos** [comment]
Hi,

I encountered the same issue, and in my case, it was due to **django-payments** being used inside an app with a namespace (plan_subscriptions). When `get_process_url` tries to **reverse process_payment**, it fails to find the correct URL.

Reference: https://github.com/jazzband/django-payments/blob/37045dfeb0303c21aba9e0df4952e7e9609a83b2/payments/models.py#L188-L189

If **django-payments** is set up in the project's root urls.py (as mentioned on the documentation), this issue does not occur.

### Workaround

To resolve this in my case, I overrode `get_process_url` in my `Transaction` model adding the namespace:

```python
class Transaction(AbstractBaseModel, BasePayment):
    user = models.ForeignKey(
        get_user_model(),
        help_text=_("The user that this subscription was billed for"),
        null=True,
        on_delete=models.SET_NULL,
        related_name="subscription_transactions",
        verbose_name=_("User"),
    )

[...]

    def get_failure_url(self):
        return f"{PAYMENT_PROTOCOL}://{PAYMENT_HOST}/subscriptions/payment-failure"

    def get_success_url(self):
        return f"{PAYMENT_PROTOCOL}://{PAYMENT_HOST}/subscriptions/payment-success"

    def get_process_url(self) -> str:
        return reverse("plan_subscriptions:process_payment", kwargs={"token": self.token})
```
